Repository sojinjang/podo-log, pull requests merged in 2023-03, with the labels that each got.

#195 [FE] 댓글 작성/수정/삭제 시 UI 업데이트 방법 개선
  client/src/components/diary-detail/Comment.tsx
  client/src/components/diary-detail/CommentSection.tsx
  client/src/components/diary-detail/CommentsFamily.tsx
  client/src/components/diary-detail/DeleteModal.tsx
  client/src/components/diary-detail/EditComment.tsx
  client/src/components/diary-detail/NewComment.tsx
  client/src/components/diary-detail/NewCommentReply.tsx
  client/src/components/diary-detail/StickerSaveBtn.tsx
  client/src/components/diary-revision/DiaryRevisionForm.tsx
  client/src/components/edit-info/EditNickname.tsx
  client/src/components/edit-info/EditPassword.tsx
  client/src/components/home/EmailLoginContainer.tsx
  client/src/components/my-page/InviteCodeSection.tsx
  client/src/components/new-diary/NewDiaryForm.tsx
  client/src/pages/BookRevision.tsx
  client/src/pages/DiaryDetail.tsx
  client/src/pages/NewBook.tsx
  client/src/recoil/diary-detail/atom.ts
  client/src/recoil/diary-detail/index.ts
Labels: ✨ enhancement, 🍇 fe, ♻️ refactor

#197 [FE] 일기장 리스트 페이지 진입 시 화면 깜빡임 버그 수정
  client/src/components/book-list/BookButton.tsx
  client/src/components/book-list/BooksContainer.tsx
  client/src/pages/BookList.tsx
Labels: 🐛 debug, 🍇 fe

#201 [BE] 토큰 만료 에러 및 토큰 생성함수 개선
  server/src/config/default.config.ts
  server/src/core/api-error.ts
  server/src/core/api-response.ts
  server/src/middlewares/required.ts
  server/src/routes/login/login-controller.ts
  server/src/types/etc-type.d.ts
  server/src/utils/create-token.ts
Labels: ✨ enhancement, 🎒 be, ♻️ refactor

#203 [BE] domain 변경후 쿠키 설정 추가
  server/src/config/default.config.ts
Labels: 🎒 be, ♻️ refactor

#206 [BE] 부모댓글 없을시 버그 수정
  server/src/config/default.config.ts
  server/src/db/sql/mockdata.sql
  server/src/db/sql/schema.sql
  server/src/passport/kakao-strategy.ts
  server/src/routes/comments/comment-service.ts
Labels: 🐞 bug, 🎒 be

#207 [BE] 부모댓글 없을시 버그 수정
  server/src/routes/comments/comment-controller.ts
Labels: 🐛 debug, 🎒 be

#204 [FE] 로그인 로직 개선 - 프론트 silent refresh 시점 변경
  client/src/components/book-setting/BookMembersInfo.tsx
  client/src/components/book-setting/InviteSection.tsx
  client/src/components/book-setting/LeaveBookButton.tsx
  client/src/components/book/DiaryListContainer.tsx
  client/src/components/diary-detail/DeleteModal.tsx
  client/src/components/diary-detail/EditComment.tsx
  client/src/components/diary-detail/NewComment.tsx
  client/src/components/diary-detail/StickerSaveBtn.tsx
  client/src/components/diary-detail/StickerSection.tsx
  client/src/components/diary-revision/DiaryRevisionForm.tsx
  client/src/components/edit-info/EditNickname.tsx
  client/src/components/edit-info/EditPassword.tsx
  client/src/components/edit-info/EditProfile.tsx
  client/src/components/grape/PackageDetail.tsx
  client/src/components/grape/StickerPackList.tsx
  client/src/components/home/EmailLoginContainer.tsx
  client/src/components/my-page/InviteCodeSection.tsx
  client/src/components/my-page/MyInfoSection.tsx
  client/src/components/my-page/SignOutButton.tsx
  client/src/components/my-page/WithdrawalButton.tsx
  client/src/components/new-diary/NewDiaryForm.tsx
  client/src/components/sign-up/EmailSignUpContainer.tsx
  client/src/pages/BookList.tsx
  client/src/pages/BookRevision.tsx
  client/src/pages/DiaryDetail.tsx
  client/src/pages/DiaryRevision.tsx
  client/src/pages/Grape.tsx
  client/src/pages/Home.tsx
  client/src/pages/NewBook.tsx
  client/src/pages/NewDiary.tsx
  client/src/recoil/diary-detail/index.ts
  client/src/recoil/token/atom.ts
  client/src/router/index.tsx
  client/src/utils/api.tsx
  client/src/utils/axiosApi/api.ts
  client/src/utils/axiosApi/defaultApi.ts
  client/src/utils/axiosApi/formApi.ts
  client/src/utils/token.ts
Labels: ✨ enhancement, 🍇 fe

#210 [FE] HEIC 이미지 파일 업로드 시 JPG로 변환시켜 업로드 가능하게 하기
  client/package.json
  client/src/components/diary-revision/DiaryRevisionImgUpload.tsx
  client/src/components/diary-revision/ExistingImg.tsx
  client/src/components/diary-revision/NewImg.tsx
  client/src/components/edit-info/EditProfile.tsx
  client/src/components/new-diary/DiaryImgUpload.tsx
  client/src/components/sign-up/ProfileImgUpload.tsx
  client/src/utils/handleHEIC.ts
Labels: 🐛 debug, 🍇 fe

#212 [FE] 이미지 post 전 압축하기
  client/package.json
  client/src/components/diary-revision/DiaryRevisionImgUpload.tsx
  client/src/components/edit-info/EditProfile.tsx
  client/src/components/new-diary/DiaryImgUpload.tsx
  client/src/components/sign-up/ProfileImgUpload.tsx
  client/src/utils/compressImg.ts
  client/src/utils/handleHEIC.ts
  client/yarn.lock
Labels: ✨ enhancement, 🐛 debug, 🍇 fe

#215 [FE] UI 개선 - 스크롤바 추가 및 숨기기, 스티커팩 박스 길이 조절
  client/package.json
  client/src/components/diary-detail/StickerSection.tsx
  client/src/components/diary/DiaryFormElem.tsx
  client/src/components/grape/PackageDetail.tsx
  client/src/components/grape/StickerPackList.tsx
  client/src/pages/BookList.tsx
  client/src/utils/axiosApi/api.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: 🍇 fe, 🎨 style

#216 [BE] maxAge 늘림
  server/src/config/default.config.ts
  server/src/middlewares/required.ts
Labels: 🎒 be

#218 [BE] 쿼리 최적화
  server/src/db/models/package.ts
Labels: 🎒 be, ♻️ refactor
