Repository sojinjang/podo-log, pull requests merged in 2023-01, with the labels that each got.

#6 [BE] 프로젝트 초기 세팅
  .github/pull_request_template.md
  server/.gitignore
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/utils/index.ts
  server/src/utils/pino.ts
  server/tsconfig.json
Labels: 🎒 be

#7 [BE] 모델 스키마 코드 작성(DDL)
  server/.gitignore
  server/src/db/schema.sql
Labels: 🎒 be

#11 [FE] 공유일기 리스트 초기화면 페이지
  client/.eslintrc.json
  client/package.json
  client/postcss.config.js
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/assets/icons/colored_grape.png
  client/src/assets/icons/colored_mypage.png
  client/src/assets/icons/colored_note.png
  client/src/assets/icons/gray_grape.png
  client/src/assets/icons/gray_mypage.png
  client/src/assets/icons/gray_note.png
  client/src/assets/icons/notebook_love.png
  client/src/assets/icons/pointing-finger.png
  client/src/components/common/Backgrounds.tsx
  client/src/components/common/NavBar.tsx
  client/src/components/diary-list/Guidance.tsx
  client/src/components/diary-list/HeartDiary.tsx
  client/src/components/diary-list/PointingFinger.tsx
  client/src/constants/ICON_DESC_PAIR_OBJ.tsx
  client/src/images.d.ts
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/pages/DiaryList.tsx
  client/src/pages/Grape.tsx
  client/src/pages/Home.tsx
  client/src/pages/LogIn.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NewDiary.tsx
  client/src/pages/NotFound.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/index.tsx
  client/src/react-app-env.d.ts
  client/src/recoil/nav-bar/atom.js
  client/src/recoil/nav-bar/index.js
  client/src/reportWebVitals.ts
  client/src/router/PrivateRouter.tsx
  client/src/router/ROUTE_INFO.tsx
  client/src/router/index.tsx
  client/src/setupTests.ts
  client/tailwind.config.js
  client/webpack.config.js
  client/yarn.lock
Labels: ✨ enhancement, 🐛 debug, 🍇 fe

#12 [BE] user 기능 추가
  server/.gitignore
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/cors.config.ts
  server/src/config/mysql.config.ts
  server/src/db/index.ts
  server/src/db/models/index.ts
  server/src/db/models/user.ts
  server/src/db/schema.sql
  server/src/db/types/user-types.ts
  server/src/middlewares/error-handler.ts
  server/src/middlewares/error-logger.ts
  server/src/middlewares/index.ts
  server/src/routes/index.ts
  server/src/routes/users/index.ts
  server/src/routes/users/schema.ts
  server/src/routes/users/user-controller.ts
  server/src/routes/users/user-service.ts
  server/src/types/etc-type.d.ts
  server/src/types/index.ts
  server/src/types/user-type.d.ts
  server/src/utils/async-handler.ts
  server/src/utils/build-query.ts
  server/src/utils/build-response.ts
  server/src/utils/index.ts
  server/src/utils/pino.ts
  server/src/utils/validator.ts
  server/tsconfig.json
Labels: ✨ enhancement, 🎒 be

#13 [FE] 공유일기 리스트 페이지
  client/package.json
  client/src/assets/icons/diary/000000.png
  client/src/assets/icons/diary/008fff.png
  client/src/assets/icons/diary/018786.png
  client/src/assets/icons/diary/2c3f50.png
  client/src/assets/icons/diary/309054.png
  client/src/assets/icons/diary/50e3c2.png
  client/src/assets/icons/diary/6200ee.png
  client/src/assets/icons/diary/82af20.png
  client/src/assets/icons/diary/b00020.png
  client/src/assets/icons/diary/e054b8.png
  client/src/assets/icons/diary/e39801.png
  client/src/assets/icons/diary/ff5436.png
  client/src/assets/icons/diary/notebook_love.png
  client/src/assets/icons/nav-bar/colored_grape.png
  client/src/assets/icons/nav-bar/colored_mypage.png
  client/src/assets/icons/nav-bar/colored_note.png
  client/src/assets/icons/nav-bar/gray_grape.png
  client/src/assets/icons/nav-bar/gray_mypage.png
  client/src/assets/icons/nav-bar/gray_note.png
  client/src/assets/icons/plus.png
  client/src/components/common/NavBar.tsx
  client/src/components/diary-list/DiaryButton.tsx
  client/src/components/diary-list/DiaryContainer.tsx
  client/src/components/diary-list/Guidance.tsx
  client/src/components/diary-list/HeartDiaryButton.tsx
  client/src/components/diary-list/NewDiaryButton.tsx
  client/src/constants/ICON_DESC_PAIR_OBJ.tsx
  client/src/pages/Diary.tsx
  client/src/pages/DiaryList.tsx
  client/src/pages/index.tsx
  client/src/recoil/nav-bar/atom.js
  client/src/router/ROUTE_INFO.tsx
  client/src/types/images.d.ts
  client/src/types/react-reveal/index.d.ts
  client/tsconfig.json
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#17 [BE] 로그인 관련 기능 task 1
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/cors.config.ts
  server/src/config/default.config.ts
  server/src/config/index.ts
  server/src/config/mysql.config.ts
  server/src/config/oauth.config.ts
  server/src/db/index.ts
  server/src/db/models/user.ts
  server/src/db/schema.sql
  server/src/db/types/user-types.ts
  server/src/middlewares/required.ts
  server/src/passport/index.ts
  server/src/passport/jwtStrategy.ts
  server/src/passport/localStrategy.ts
  server/src/routes/index.ts
  server/src/routes/login/index.ts
  server/src/routes/login/login-controller.ts
  server/src/routes/login/schema.ts
  server/src/routes/users/index.ts
  server/src/routes/users/user-controller.ts
  server/src/routes/users/user-service.ts
  server/src/types/index.ts
  server/src/types/login-type.d.ts
  server/src/types/user-type.d.ts
  server/src/utils/async-handler.ts
  server/src/utils/index.ts
  server/src/utils/pino.ts
  server/src/utils/validator.ts
  server/tsconfig.json
Labels: ✨ enhancement, 🐛 debug, 🎒 be

#20 [BE] 일기장 기능 추가
  server/src/db/models/book.ts
  server/src/db/models/index.ts
  server/src/db/models/user.ts
  server/src/db/schema.sql
  server/src/middlewares/index.ts
  server/src/passport/index.ts
  server/src/routes/books/book-controller.ts
  server/src/routes/books/book-service.ts
  server/src/routes/books/index.ts
  server/src/routes/books/schema.ts
  server/src/routes/index.ts
  server/src/routes/login/index.ts
  server/src/routes/users/index.ts
  server/src/types/book-type.d.ts
  server/src/types/etc-type.d.ts
  server/src/types/index.ts
  server/src/utils/build-query.ts
Labels: ✨ enhancement, 🎒 be

#21 [FE] 일기장 생성 페이지
  client/src/assets/icons/arrow_back.png
  client/src/components/common/BackButton.tsx
  client/src/components/common/Backgrounds.tsx
  client/src/components/common/PageTitle.tsx
  client/src/components/common/PurpleButton.css
  client/src/components/common/PurpleButton.tsx
  client/src/components/new-diary/ColorSelectContainer.tsx
  client/src/components/new-diary/ContainerTitle.tsx
  client/src/components/new-diary/DiaryIcon.tsx
  client/src/components/new-diary/DiaryTitleInputContainer.tsx
  client/src/constants/DIARY_COLOR.tsx
  client/src/constants/WARNING_MESSAGE.tsx
  client/src/index.css
  client/src/pages/NewDiary.tsx
  client/src/recoil/new-diary/atom.js
  client/src/recoil/new-diary/index.js
  client/tailwind.config.js
Labels: ✨ enhancement, 🐛 debug, 🍇 fe, 🎨 style

#22 [BE] 카카오 로그인 기능
  server/src/db/schema.sql
  server/src/passport/index.ts
  server/src/passport/kakaoStrategy.ts
  server/src/routes/login/login-controller.ts
  server/src/types/user-type.d.ts
Labels: ✨ enhancement, 🎒 be

#25 [BE] diary(일기장) 기능 추가
  server/src/db/models/diary.ts
  server/src/db/models/index.ts
  server/src/routes/books/book-service.ts
  server/src/routes/books/index.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/diaries/index.ts
  server/src/routes/diaries/schema.ts
  server/src/routes/index.ts
  server/src/routes/login/schema.ts
  server/src/routes/users/schema.ts
  server/src/types/diary-type.d.ts
  server/src/types/index.ts
Labels: ✨ enhancement, 🎒 be

#27 [FE] 홈화면 페이지
  client/package.json
  client/src/assets/grape/grape_0.png
  client/src/assets/grape/grape_1.png
  client/src/assets/grape/grape_2.png
  client/src/assets/grape/grape_3.png
  client/src/assets/grape/grape_4.png
  client/src/assets/grape/grape_5.png
  client/src/assets/grape/grape_6.png
  client/src/assets/grape/grape_7.png
  client/src/assets/grape/grape_8.png
  client/src/assets/icons/sns/kakao.png
  client/src/assets/icons/sns/naver.png
  client/src/components/common/Backgrounds.css
  client/src/components/common/Backgrounds.tsx
  client/src/components/common/PurpleButton.tsx
  client/src/components/home/EmailLoginContainer.tsx
  client/src/components/home/GrapeIcon.tsx
  client/src/components/home/Greeting.tsx
  client/src/components/home/SNSLoginContainer.tsx
  client/src/components/home/SignUpButton.tsx
  client/src/constants/API_URL.tsx
  client/src/constants/Keys.tsx
  client/src/pages/Home.tsx
  client/src/pages/LogIn.tsx
  client/src/pages/NewDiary.tsx
  client/src/pages/index.tsx
  client/src/router/ROUTE_INFO.tsx
  client/src/utils/api.tsx
  client/src/utils/cookie.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#29 [BE] 로그인 응답을 쿠키+redirect 로 전환
  .gitignore
  client/.gitignore
  package-lock.json
  package.json
  server/src/config/default.config.ts
  server/src/routes/login/login-controller.ts
Labels: ✨ enhancement, 🎒 be

#31 [BE] diary 페이징 추가
  package.json
  server/package.json
  server/src/db/models/diary.ts
  server/src/routes/books/index.ts
  server/src/routes/books/schema.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/types/diary-type.d.ts
  server/src/utils/build-query.ts
Labels: ✨ enhancement, 🎒 be

#33 [BE] 댓글 기능 추가
  server/src/db/models/comment.ts
  server/src/db/models/diary.ts
  server/src/db/models/index.ts
  server/src/routes/comments/comment-controller.ts
  server/src/routes/comments/comment-service.ts
  server/src/routes/comments/index.ts
  server/src/routes/comments/schema.ts
  server/src/routes/index.ts
  server/src/types/comment-type.d.ts
  server/src/types/index.ts
  server/src/utils/build-query.ts
Labels: ✨ enhancement, 🎒 be

#37 [FE] 공유일기장 내부 - 글 리스트 페이지
  client/package.json
  client/src/assets/IMG_7291.JPG
  client/src/assets/icons/comment.png
  client/src/assets/icons/pencil.png
  client/src/assets/icons/setting.png
  client/src/assets/profile.jpg
  client/src/components/book-list/BookButton.tsx
  client/src/components/book-list/BooksContainer.tsx
  client/src/components/book-list/Guidance.tsx
  client/src/components/book-list/HeartDiaryButton.tsx
  client/src/components/book-list/NewBookButton.tsx
  client/src/components/book-list/PointingFinger.tsx
  client/src/components/book/BookName.tsx
  client/src/components/book/DiaryContainer.tsx
  client/src/components/book/DiaryListContainer.tsx
  client/src/components/book/NewDiaryButton.tsx
  client/src/components/book/SettingButton.tsx
  client/src/components/common/BackButton.tsx
  client/src/components/common/NavBar.tsx
  client/src/components/common/PageTitle.tsx
  client/src/components/home/EmailLoginContainer.tsx
  client/src/components/new-book/ColorSelectContainer.tsx
  client/src/components/new-book/ContainerTitle.tsx
  client/src/components/new-book/DiaryIcon.tsx
  client/src/components/new-book/DiaryTitleInputContainer.tsx
  client/src/constants/API_URL.tsx
  client/src/constants/ICON_DESC_PAIR_OBJ.tsx
  client/src/pages/Book.tsx
  client/src/pages/BookList.tsx
  client/src/pages/BookSetting.tsx
  client/src/pages/Diary.tsx
  client/src/pages/DiaryDetail.tsx
  client/src/pages/Home.tsx
  client/src/pages/NewBook.tsx
  client/src/pages/NewDiary.tsx
  client/src/pages/index.tsx
  client/src/recoil/nav-bar/atom.js
  client/src/router/ROUTE_INFO.tsx
  client/src/utils/hooks.js
  client/src/utils/time.tsx
  client/yarn.lock
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#41 [BE] refresh 토큰 task 1
  server/src/config/default.config.ts
  server/src/passport/access-jwt-strategy.ts
  server/src/passport/index.ts
  server/src/passport/kakao-strategy.ts
  server/src/passport/local-strategy.ts
  server/src/passport/refresh-jwt-strategy.ts
  server/src/routes/login/index.ts
  server/src/routes/login/login-controller.ts
  server/src/utils/create-token.ts
  server/src/utils/index.ts
  server/src/utils/parse-cookies.ts
Labels: ✨ enhancement, 🐛 debug, 🎒 be

#42 [BE] refresh 기능 추가
  client/src/utils/api.tsx
  server/src/config/default.config.ts
  server/src/middlewares/required.ts
  server/src/routes/login/login-controller.ts
Labels: ✨ enhancement, 🐛 debug, 🎒 be

#43 [BE] 컨트롤러 내부 파라미터 추가
  server/src/routes/login/login-controller.ts
Labels: 🐛 debug, 🎒 be

#44 Feat/be/fix
  server/src/passport/access-jwt-strategy.ts
  server/src/passport/index.ts
  server/src/passport/refresh-jwt-strategy.ts
Labels: 🐛 debug, 🎒 be

#47 [BE] logout 버그 수정
  server/src/routes/login/index.ts
  server/src/routes/login/login-controller.ts
  server/src/routes/login/schema.ts
Labels: 🐛 debug, 🎒 be

#48 [BE] 이미지 기능
  server/package-lock.json
  server/package.json
  server/src/config/aws-s3.config.ts
  server/src/config/default.config.ts
  server/src/config/index.ts
  server/src/db/schema.sql
  server/src/middlewares/index.ts
  server/src/middlewares/multer-s3.ts
  server/src/routes/books/schema.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/diaries/index.ts
  server/src/routes/diaries/schema.ts
  server/src/routes/users/index.ts
  server/src/routes/users/user-controller.ts
  server/src/routes/users/user-service.ts
  server/src/types/diary-type.d.ts
  server/src/types/login-type.d.ts
  server/src/types/user-type.d.ts
Labels: ✨ enhancement, 🐛 debug, 🎒 be

#50 [BE] naver 로그인 기능 추가
  server/package-lock.json
  server/package.json
  server/src/config/oauth.config.ts
  server/src/passport/index.ts
  server/src/passport/naver-strategy.ts
  server/src/routes/login/index.ts
  server/src/routes/login/login-controller.ts
Labels: ✨ enhancement, 🎒 be

#52 [BE] 에러 응답 return 추가
  server/src/routes/books/book-controller.ts
  server/src/routes/comments/comment-controller.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/login/login-controller.ts
  server/src/routes/users/user-controller.ts
Labels: 🐛 debug, 🎒 be

#54 [BE] numComments 추가
  server/src/db/models/diary.ts
Labels: ✨ enhancement, 🎒 be

#55 [BE] numMembers 추가
  server/src/db/models/book.ts
  server/src/db/schema.sql
Labels: ✨ enhancement, 🎒 be

#57 [BE] sns로그인 성공시 쿼리추가
  server/src/routes/login/login-controller.ts
Labels: 🎒 be

#58 [FE] OAuth access token 발급 후 일기장 리스트 페이지로 자동 redirect
  client/package.json
  client/src/constants/API_URL.tsx
  client/src/pages/Home.tsx
  client/src/recoil/token/atom.ts
  client/src/recoil/token/index.ts
  client/src/utils/token.ts
  client/yarn.lock
Labels: ✨ enhancement, 🐛 debug, 🍇 fe
