Repository sojinjang/podo-log, pull requests merged in 2023-02, with the labels that each got.

#60 [FE] 소셜 로그인 기능 완성, access token 자동 갱신 기능 추가
  client/src/components/home/EmailLoginContainer.tsx
  client/src/components/home/SNSLoginContainer.tsx
  client/src/pages/Home.tsx
  client/src/router/PrivateRouter.tsx
  client/src/router/index.tsx
  client/src/utils/api.tsx
  client/src/utils/token.ts
Labels: ✨ enhancement, 🐛 debug, 🍇 fe

#61 [BE] 초대 코드 기능 추가
  server/src/db/models/book.ts
  server/src/db/models/index.ts
  server/src/db/models/invtt-code.ts
  server/src/db/schema.sql
  server/src/routes/books/book-controller.ts
  server/src/routes/books/book-service.ts
  server/src/routes/books/index.ts
  server/src/routes/invtt-code/index.ts
  server/src/routes/invtt-code/invtt-code-controller.ts
  server/src/routes/invtt-code/invtt-code-service.ts
  server/src/routes/invtt-code/schema.ts
  server/src/routes/users/user-service.ts
  server/src/types/book-type.d.ts
  server/src/types/index.ts
  server/src/types/invtt-code-type.d.ts
  server/src/utils/create-invtt-code.ts
  server/src/utils/index.ts
Labels: ✨ enhancement, 🎒 be

#63 [BE] 일기장 들어가기 기능 추가
  server/src/db/models/book.ts
  server/src/db/models/index.ts
  server/src/db/models/invtt-code.ts
  server/src/db/models/user-book.ts
  server/src/routes/books/book-service.ts
  server/src/routes/invtt-code/index.ts
  server/src/routes/invtt-code/invtt-code-controller.ts
  server/src/routes/invtt-code/invtt-code-service.ts
  server/src/routes/invtt-code/schema.ts
  server/src/types/invtt-code-type.d.ts
Labels: ✨ enhancement, 🎒 be

#65 [BE] user 응답 개선
  server/src/app.ts
  server/src/core/api-error.ts
  server/src/core/api-response.ts
  server/src/db/models/book.ts
  server/src/db/models/comment.ts
  server/src/db/models/diary.ts
  server/src/db/models/user-book.ts
  server/src/db/models/user.ts
  server/src/db/schema.sql
  server/src/middlewares/error-handler.ts
  server/src/routes/users/index.ts
  server/src/routes/users/user-controller.ts
  server/src/routes/users/user-service.ts
  server/src/types/etc-type.d.ts
  server/src/utils/build-response.ts
  server/src/utils/check-result.ts
  server/src/utils/index.ts
  server/src/utils/validator.ts
  server/tsconfig.json
Labels: ✨ enhancement, 🎒 be

#67 [BE] user 라우팅 fix
  server/src/config/aws-s3.config.ts
  server/src/middlewares/multer-s3.ts
  server/src/routes/users/index.ts
Labels: 🐛 debug, 🎒 be

#69 [BE] login 응답 수정
  server/src/middlewares/multer-s3.ts
  server/src/middlewares/required.ts
  server/src/routes/login/login-controller.ts
  server/src/routes/users/index.ts
  server/src/routes/users/user-controller.ts
  server/src/utils/validator.ts
Labels: ✨ enhancement, 🎒 be

#66 [FE] 회원가입 페이지
  client/src/assets/icons/default_profile.png
  client/src/components/common/Input.tsx
  client/src/components/home/EmailLoginContainer.tsx
  client/src/components/home/SNSLoginContainer.tsx
  client/src/components/sign-up/EmailSignUpContainer.tsx
  client/src/components/sign-up/ProfileImgUpload.tsx
  client/src/constants/API_URL.tsx
  client/src/pages/Home.tsx
  client/src/pages/SignUp.tsx
  client/src/recoil/sign-up/atom.ts
  client/src/recoil/sign-up/index.ts
  client/src/utils/api.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#71 [BE] 에러 및 응답 정리
  server/src/middlewares/error-logger.ts
  server/src/routes/books/book-controller.ts
  server/src/routes/books/book-service.ts
  server/src/routes/comments/comment-controller.ts
  server/src/routes/comments/comment-service.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/invtt-code/invtt-code-controller.ts
  server/src/routes/invtt-code/invtt-code-service.ts
  server/src/routes/users/index.ts
  server/src/routes/users/user-controller.ts
  server/src/routes/users/user-service.ts
  server/src/types/etc-type.d.ts
  server/src/utils/check-result.ts
Labels: ✨ enhancement, 🎒 be

#72 [FE] headers authorization token 주기, api 변경에 따른 코드 수정
  client/src/components/book-list/BookButton.tsx
  client/src/components/book-list/BooksContainer.tsx
  client/src/components/book/DiaryContainer.tsx
  client/src/components/book/DiaryListContainer.tsx
  client/src/components/home/EmailLoginContainer.tsx
  client/src/constants/API_URL.tsx
  client/src/constants/Keys.tsx
  client/src/pages/BookList.tsx
  client/src/utils/api.tsx
  client/src/utils/token.ts
Labels: ✨ enhancement, 🍇 fe

#73 [BE] 로그인 응답 class 추가
  server/src/config/default.config.ts
  server/src/core/api-error.ts
  server/src/core/api-response.ts
  server/src/passport/kakao-strategy.ts
  server/src/routes/comments/comment-service.ts
  server/src/routes/login/login-controller.ts
Labels: ✨ enhancement, 🎒 be

#75 [#74] :bug: fix(login): 에러발생시 건너뛰지 안았던 버그 fix
  server/src/routes/login/login-controller.ts
Labels: 🐛 debug, 🎒 be

#81 [BE] #78 버그 fix
  server/src/routes/diaries/index.ts
Labels: 🐛 debug, 🎒 be

#77 [FE] 공유일기장 내부 - 일기 작성 페이지
  client/src/assets/icons/image.png
  client/src/assets/icons/trash-can-white.png
  client/src/components/book/NewDiaryButton.tsx
  client/src/components/new-book/BookTitleInputContainer.tsx
  client/src/components/new-book/ColorSelectContainer.tsx
  client/src/components/new-book/DiaryIcon.tsx
  client/src/components/new-diary/DiaryImgUpload.tsx
  client/src/components/new-diary/NewDiaryForm.tsx
  client/src/components/new-diary/PostButton.tsx
  client/src/constants/API_URL.tsx
  client/src/pages/NewBook.tsx
  client/src/pages/NewDiary.tsx
  client/src/recoil/new-book/atom.js
  client/src/recoil/new-book/index.js
  client/src/recoil/new-diary/atom.ts
  client/src/recoil/new-diary/index.js
  client/src/recoil/new-diary/index.ts
  client/src/router/ROUTE_INFO.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#83 [BE] 일기 최신순 조회
  server/src/db/models/diary.ts
Labels: 🐛 debug, 🎒 be

#85 [BE] s3 저장 경로 분리
  server/src/middlewares/multer-s3.ts
  server/src/middlewares/required.ts
Labels: 🎒 be

#86 [FE] 일기장 생성 페이지 api 연결, 디자인 수정 및 리팩토링
  client/src/components/common/PurpleButton.tsx
  client/src/components/new-book/BookTitleInputContainer.tsx
  client/src/components/new-book/ColorSelectContainer.tsx
  client/src/constants/WARNING_MESSAGE.tsx
  client/src/pages/NewBook.tsx
  client/src/recoil/new-book/atom.js
  client/src/recoil/new-book/index.js
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#87 [FE] 404 페이지
  client/src/assets/icons/404-error.png
  client/src/pages/NotFound.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#91 [BE] book members 조회에 isMe 추가
  server/src/routes/books/book-service.ts
Labels: ✨ enhancement, 🎒 be

#93 [BE]1차 mockdata
  server/src/db/mockdata.sql
Labels: ✨ enhancement, 🎒 be

#97 Revert "[BE]1차 mockdata"
  server/src/db/mockdata.sql
Labels: 🎒 be

#98 [BE] 1차 mockdata
  server/src/db/mockdata.sql
  server/src/db/schema.sql
Labels: ✨ enhancement, 🎒 be

#96 [FE] 일기장 설정 페이지, 수정 페이지
  client/src/assets/icons/refresh.png
  client/src/components/book-list/BookButton.tsx
  client/src/components/book-setting/BookMembersInfo.tsx
  client/src/components/book-setting/BookRevisionButton.tsx
  client/src/components/book-setting/ClickableContainer.tsx
  client/src/components/book-setting/InviteSection.tsx
  client/src/components/book-setting/LeaveBookButton.tsx
  client/src/components/book-setting/MemberProfile.tsx
  client/src/components/book/DiaryContainer.tsx
  client/src/components/book/SettingButton.tsx
  client/src/components/common/PurpleButton.css
  client/src/components/common/PurpleButton.tsx
  client/src/components/new-book/ColorSelectContainer.tsx
  client/src/components/new-book/DiaryIcon.tsx
  client/src/constants/API_URL.tsx
  client/src/pages/BookRevision.tsx
  client/src/pages/BookSetting.tsx
  client/src/pages/Home.tsx
  client/src/pages/NewBook.tsx
  client/src/pages/index.tsx
  client/src/recoil/book-color/atom.js
  client/src/recoil/book-color/index.js
  client/src/router/ROUTE_INFO.tsx
  client/src/router/index.tsx
  client/src/utils/api.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#102 [BE] timezone, isBookMember 추가
  server/src/config/mysql.config.ts
  server/src/db/mockdata.sql
  server/src/middlewares/required.ts
  server/src/routes/books/book-controller.ts
  server/src/routes/books/book-service.ts
  server/src/routes/books/index.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/diaries/index.ts
Labels: ✨ enhancement, 🐛 debug, 🎒 be

#103 Fix/fe/#101 post photo
  client/src/components/new-diary/NewDiaryForm.tsx
  client/src/components/sign-up/EmailSignUpContainer.tsx
Labels: 🐛 debug, 🍇 fe

#104 [BE] 포도알 기능, 트리거
  server/src/db/index.ts
  server/src/db/models/user.ts
  server/src/db/schema.sql
  server/src/db/trigger.sql
  server/src/routes/users/index.ts
  server/src/routes/users/user-controller.ts
  server/src/routes/users/user-service.ts
  server/src/utils/check-result.ts
Labels: ✨ enhancement, 🎒 be

#106 [BE] 댓글 조회 정보에 user 추가
  server/src/db/models/comment.ts
Labels: ✨ enhancement, 🎒 be

#109 [BE] 글자수 체크
  server/src/db/schema.sql
  server/src/routes/comments/schema.ts
  server/src/routes/diaries/schema.ts
Labels: ✨ enhancement, 🐛 debug, 🎒 be

#111 [BE] 댓글 조회 응답 개선
  server/src/routes/comments/comment-service.ts
  server/src/types/etc-type.d.ts
Labels: ✨ enhancement, 🎒 be

#112 [BE] mock데이터 댓글 숫자 지움
  server/src/db/mockdata.sql
  server/src/db/schema.sql
Labels: 🎒 be

#114 [BE] comment 조회시 빈데이터 처리
  server/src/routes/comments/comment-service.ts
Labels: 🐛 debug, 🎒 be

#107 [FE] 게시글 상세 페이지 - 댓글 보여주기, 댓글 달기
  client/src/assets/icons/sticker.png
  client/src/components/book/DiaryContainer.tsx
  client/src/components/common/WriterInfo.tsx
  client/src/components/diary-detail/Comment.tsx
  client/src/components/diary-detail/CommentSection.tsx
  client/src/components/diary-detail/DetailedDiaryContainer.tsx
  client/src/components/diary-detail/NewComment.tsx
  client/src/components/diary-detail/StickerButton.tsx
  client/src/components/new-diary/NewDiaryForm.tsx
  client/src/constants/API_URL.tsx
  client/src/pages/DiaryDetail.tsx
  client/tailwind.config.js
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#116 [FE] 게시글 상세 페이지 - 댓글의 답글 달기
  client/src/assets/icons/reply.png
  client/src/components/diary-detail/Comment.tsx
  client/src/components/diary-detail/CommentSection.tsx
  client/src/components/diary-detail/CommentsFamily.tsx
  client/src/components/diary-detail/NewComment.tsx
  client/src/components/diary-detail/ReplyComment.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#120 [BE] 이미지 도메인 빼고 key 값만 저장
  server/.gitignore
  server/src/config/default.config.ts
  server/src/db/mockdata.sql
  server/src/db/schema.sql
  server/src/middlewares/multer-s3.ts
  server/src/routes/comments/comment-service.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/users/user-controller.ts
  server/src/routes/users/user-service.ts
  server/src/types/login-type.d.ts
  server/src/utils/build-image-location.ts
  server/src/utils/index.ts
  server/tsconfig.json
Labels: ✨ enhancement, 🎒 be

#123 [FE] 게시글 상세 페이지 - 댓글 작성자 댓글 수정, 삭제
  client/src/components/common/PurpleButton.tsx
  client/src/components/diary-detail/Comment.tsx
  client/src/components/diary-detail/DeleteModal.tsx
  client/src/components/diary-detail/DetailedDiaryContainer.tsx
  client/src/components/diary-detail/DropdownMenu.tsx
  client/src/components/diary-detail/EditComment.tsx
  client/src/recoil/diary-detail/atom.ts
  client/src/recoil/diary-detail/index.ts
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#126 [FE] 다이어리 사진 경로 "없음" 아닐때만 보여주기
  client/src/components/book/DiaryContainer.tsx
  client/src/components/diary-detail/DetailedDiaryContainer.tsx
Labels: 🐛 debug, 🍇 fe

#127 [BE] package 와 sticker 업로드 기능 추가
  server/package-lock.json
  server/package.json
  server/src/config/aws-s3.config.ts
  server/src/db/models/index.ts
  server/src/db/models/package.ts
  server/src/middlewares/multer-s3.ts
  server/src/routes/index.ts
  server/src/routes/packages/index.ts
  server/src/routes/packages/package-controller.ts
  server/src/routes/packages/package-service.ts
  server/src/routes/packages/schema.ts
  server/src/types/index.ts
  server/src/types/login-type.d.ts
  server/src/types/package-type.d.ts
  server/src/utils/build-query.ts
  server/src/utils/image-upload-with-resizing.ts
  server/src/utils/index.ts
Labels: ✨ enhancement, 🎒 be

#130 [BE] diaryId로 일기 조회
  server/src/routes/books/index.ts
  server/src/routes/books/schema.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/diaries/index.ts
Labels: ✨ enhancement, 🎒 be

#131 [BE] 패키지 구매 기능 추가
  server/src/db/models/package.ts
  server/src/db/schema.sql
  server/src/routes/packages/index.ts
  server/src/routes/packages/package-controller.ts
  server/src/routes/packages/package-service.ts
  server/src/routes/packages/schema.ts
  server/src/types/package-type.d.ts
Labels: ✨ enhancement, 🎒 be

#135 [BE] 조회기능 추가
  server/src/db/models/package.ts
  server/src/db/schema.sql
  server/src/routes/packages/index.ts
  server/src/routes/packages/package-controller.ts
  server/src/routes/packages/package-service.ts
  server/src/types/package-type.d.ts
  server/src/utils/build-query.ts
  server/src/utils/check-expiration-package.ts
  server/src/utils/index.ts
Labels: ✨ enhancement, 🎒 be

#139 [BE] 패키지 삭제 및 S3 이미지 삭제
  server/src/db/models/package.ts
  server/src/middlewares/multer-s3.ts
  server/src/routes/packages/index.ts
  server/src/routes/packages/package-controller.ts
  server/src/routes/packages/package-service.ts
Labels: ✨ enhancement, 🎒 be

#140 [BE] 라우팅 코드 순서 변경
  server/src/routes/packages/index.ts
Labels: 🐛 debug, 🎒 be

#142 [BE] 이미지 도메인 추가
  server/src/routes/packages/package-service.ts
Labels: 🐛 debug, 🎒 be

#145 [BE] 스티커 붙이기 기능
  server/src/db/mockdata.sql
  server/src/db/models/diary.ts
  server/src/db/schema.sql
  server/src/db/set-package.sql
  server/src/db/trigger.sql
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/diaries/index.ts
  server/src/routes/diaries/schema.ts
  server/src/types/diary-type.d.ts
  server/src/types/invtt-code-type.d.ts
  server/src/utils/build-query.ts
Labels: ✨ enhancement, 🎒 be

#147 [BE] 기본 패키지 구분 적용
  server/src/config/default.config.ts
  server/src/db/models/user.ts
  server/src/middlewares/required.ts
  server/src/routes/packages/index.ts
  server/src/routes/packages/package-controller.ts
  server/src/routes/packages/package-service.ts
  server/src/utils/check-expiration-package.ts
Labels: ✨ enhancement, 🎒 be

#148 [BE] 괄호 수정
  server/src/db/schema.sql
  server/src/routes/packages/package-controller.ts
Labels: 🐛 debug, 🎒 be

#150 [BE] package 데이터 추가
  server/src/db/sql/default-package.sql
  server/src/db/sql/mockdata.sql
  server/src/db/sql/packages.sql
  server/src/db/sql/schema.sql
  server/src/db/sql/stickers.sql
  server/src/db/sql/trigger.sql
  server/src/middlewares/multer-s3.ts
  server/src/routes/diaries/index.ts
  server/src/routes/packages/index.ts
  server/src/routes/users/index.ts
Labels: ✨ enhancement, 🎒 be

#152 [BE] 붙은 스티커 조회
  server/src/db/models/diary.ts
  server/src/db/sql/mockdata.sql
  server/src/routes/diaries/diary-service.ts
  server/src/utils/build-image-location.ts
Labels: ✨ enhancement, 🎒 be

#153 [BE] mockdata url 공백 수정
  server/src/db/sql/mockdata.sql
  server/src/db/sql/stickers.sql
  server/src/routes/packages/package-service.ts
  server/src/utils/image-upload-with-resizing.ts
Labels: 🐛 debug, 🎒 be

#156 [FE] 게시글 상세 페이지 - 스티커 붙이기/떼기/움직이기, 저장
  client/package.json
  client/src/assets/icons/x.png
  client/src/components/diary-detail/CommentSection.tsx
  client/src/components/diary-detail/CommentsFamily.tsx
  client/src/components/diary-detail/DetailedDiaryContainer.tsx
  client/src/components/diary-detail/DiarySection.tsx
  client/src/components/diary-detail/DiarySectionContainer.tsx
  client/src/components/diary-detail/MoveableSticker.tsx
  client/src/components/diary-detail/NewComment.tsx
  client/src/components/diary-detail/StickerButton.tsx
  client/src/components/diary-detail/StickerSaveBtn.tsx
  client/src/components/diary-detail/StickerSection.tsx
  client/src/components/diary/PostButton.tsx
  client/src/constants/API_URL.ts
  client/src/constants/Values.ts
  client/src/pages/DiaryDetail.tsx
  client/src/recoil/diary-detail/atom.ts
  client/src/utils/convertCoord.ts
  client/src/utils/date.ts
  client/yarn.lock
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#161 [BE] 다이어리별 스티커 조회
  server/src/db/index.ts
  server/src/db/models/diary.ts
  server/src/routes/diaries/diary-controller.ts
  server/src/routes/diaries/diary-service.ts
  server/src/routes/diaries/index.ts
Labels: ✨ enhancement, 🎒 be

#163 [BE] 스티커 붙이기 응답에 조회 내용 추가
  server/src/routes/diaries/diary-service.ts
Labels: ✨ enhancement, 🎒 be

#164 [FE] 게시글 상세 페이지 - 붙은 스티커 보여주기, drag and drop 기능
  client/src/components/common/diary/DiarySection.tsx
  client/src/components/common/diary/DiarySectionContainer.tsx
  client/src/components/common/diary/Sticker.tsx
  client/src/components/common/diary/WriterInfo.tsx
  client/src/components/diary-detail/DeleteModal.tsx
  client/src/components/diary-detail/DeleteWarningModal.tsx
  client/src/components/diary-detail/DropdownMenu.tsx
  client/src/components/diary-detail/EditingSticker.tsx
  client/src/components/diary-detail/StickerButton.tsx
  client/src/components/diary-detail/StickerSaveBtn.tsx
  client/src/pages/DiaryDetail.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#166 [FE] 글 리스트 페이지 - 붙은 스티커 보여주기, drag and drop 기능
  client/src/components/book/DiaryContainer.tsx
  client/src/components/book/DiaryListContainer.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#168 [BE] 일기리스트 조회에 스티커 정렬 추가
  server/src/db/models/diary.ts
Labels: ✨ enhancement, 🎒 be

#173 [FE] Navigation Bar 기능 완성, css 보완
  client/src/components/common/Backgrounds.tsx
  client/src/components/common/NavBar.tsx
  client/src/pages/BookList.tsx
  client/src/recoil/nav-bar/atom.js
  client/src/recoil/nav-bar/index.js
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#174 [FE] 포도알 페이지 - 내 포도
  client/src/assets/icons/move_down.png
  client/src/assets/icons/move_up.png
  client/src/components/common/Backgrounds.css
  client/src/components/common/NavBar.tsx
  client/src/components/grape/GrapeInfo.tsx
  client/src/components/grape/MoveBtn.tsx
  client/src/constants/API_URL.ts
  client/src/pages/BookList.tsx
  client/src/pages/Grape.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#176 [BE] 클라이언트 서버 origin주소 변경
  server/src/config/default.config.ts
Labels: 🐛 debug, 🎒 be

#178 [BE] DB주소 이전
  server/src/config/mysql.config.ts
Labels: 🎒 be

#179 [FE] 포도알 페이지 - 스티커 샵
  client/src/assets/icons/colored_grape_353866.png
  client/src/assets/icons/grape.png
  client/src/components/grape/GrapeInfo.tsx
  client/src/components/grape/MoveBtn.tsx
  client/src/components/grape/MyGrapeNum.tsx
  client/src/components/grape/PackageDetail.tsx
  client/src/components/grape/Sticker.tsx
  client/src/components/grape/StickerPackList.tsx
  client/src/components/grape/purchaseButton.css
  client/src/constants/API_URL.ts
  client/src/pages/Grape.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#170 [FE] Github Actions로 dev 브랜치 FE 코드 gh-pages 자동 배포
  .github/workflows/client.yml
  client/package.json
  client/public/index.html
  client/src/components/book-list/BooksContainer.tsx
  client/src/components/book-setting/BookMembersInfo.tsx
  client/src/components/book-setting/InviteSection.tsx
  client/src/components/book/DiaryListContainer.tsx
  client/src/components/common/diary/Sticker.tsx
  client/src/components/diary-detail/CommentSection.tsx
  client/src/components/diary-detail/EditingSticker.tsx
  client/src/components/diary-detail/StickerSection.tsx
  client/src/components/diary-revision/DiaryRevisionImgUpload.tsx
  client/src/components/grape/GrapeInfo.tsx
  client/src/components/grape/MoveBtn.tsx
  client/src/components/grape/Sticker.tsx
  client/src/components/grape/StickerPackList.tsx
  client/src/pages/DiaryDetail.tsx
  client/src/pages/Grape.tsx
  client/src/pages/Home.tsx
  client/src/router/index.tsx
  client/src/utils/hooks.js
Labels: 🍇 fe

#184 [BE] 약한탈퇴 조회 제외
  server/src/db/models/user.ts
  server/src/passport/kakao-strategy.ts
  server/src/passport/naver-strategy.ts
  server/src/routes/users/user-service.ts
Labels: ✨ enhancement, 🎒 be

#185 [FE] 마이페이지 - 마이페이지 메인
  client/src/components/book-setting/BookRevisionButton.tsx
  client/src/components/book-setting/LeaveBookButton.tsx
  client/src/components/book/DiaryContainer.tsx
  client/src/components/common/ClickableContainer.tsx
  client/src/components/common/UnclickableContainer.tsx
  client/src/components/diary-detail/Comment.tsx
  client/src/components/my-page/InviteCodeSection.tsx
  client/src/components/my-page/MyInfoSection.tsx
  client/src/components/my-page/SignOutButton.tsx
  client/src/components/my-page/WithdrawalButton.tsx
  client/src/constants/API_URL.ts
  client/src/pages/DiaryDetail.tsx
  client/src/pages/EditInfo.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/index.tsx
  client/src/router/ROUTE_INFO.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#187 [FE] 마이페이지 - 내 정보 수정
  client/src/components/common/Input.tsx
  client/src/components/common/Profile.tsx
  client/src/components/common/PurpleButton.tsx
  client/src/components/edit-info/EditNickname.tsx
  client/src/components/edit-info/EditPassword.tsx
  client/src/components/edit-info/EditProfile.tsx
  client/src/components/edit-info/NewProfile.tsx
  client/src/components/edit-info/OriginalProfile.tsx
  client/src/components/sign-up/ProfileImgUpload.tsx
  client/src/constants/API_URL.ts
  client/src/pages/EditInfo.tsx
Labels: ✨ enhancement, 🍇 fe, 🎨 style

#188 [#] :truck: chore: server 주소 추가
  server/src/config/default.config.ts
  server/src/config/oauth.config.ts
Labels: 🎒 be

#191 [FE] 디자인 보완, 반응형 크기 수정
  client/src/components/book-list/BookButton.tsx
  client/src/components/book-list/Guidance.tsx
  client/src/components/book-setting/BookMembersInfo.tsx
  client/src/components/book-setting/InviteSection.tsx
  client/src/components/book-setting/MemberProfile.tsx
  client/src/components/book/DiaryContainer.tsx
  client/src/components/book/SettingButton.tsx
  client/src/components/common/BackButton.tsx
  client/src/components/common/ClickableContainer.tsx
  client/src/components/common/Input.tsx
  client/src/components/common/PageTitle.tsx
  client/src/components/diary-detail/DeleteModal.tsx
  client/src/components/diary-detail/DropdownMenu.tsx
  client/src/components/diary-detail/EditComment.tsx
  client/src/components/diary-detail/NewComment.tsx
  client/src/components/diary-detail/ReplyComment.tsx
  client/src/components/diary-detail/StickerSaveBtn.tsx
  client/src/components/diary-detail/StickerSection.tsx
  client/src/components/diary/DiaryFormElem.tsx
  client/src/components/diary/PostButton.tsx
  client/src/components/edit-info/EditPassword.tsx
  client/src/components/grape/PackageDetail.tsx
  client/src/components/grape/StickerPackList.tsx
  client/src/components/home/Greeting.tsx
  client/src/components/home/SNSLoginContainer.tsx
  client/src/components/home/SignUpButton.tsx
  client/src/components/new-book/BookTitleInputContainer.tsx
  client/src/components/new-book/ColorSelectContainer.tsx
  client/src/components/new-book/ContainerTitle.tsx
  client/src/components/sign-up/EmailSignUpContainer.tsx
  client/src/index.css
  client/src/pages/NotFound.tsx
  client/tailwind.config.js
Labels: 🍇 fe, 🎨 style

#192 [FE] 반응형 크기 조절
  client/src/components/book-list/NewBookButton.tsx
  client/src/components/common/PurpleButton.tsx
  client/src/components/diary-detail/DeleteModal.tsx
  client/src/components/diary-detail/StickerButton.tsx
Labels: 🍇 fe, 🎨 style

#193 [FEATURE] file object 변환없이 기존 이미지 수정 기능 구현
  client/src/components/diary-revision/DiaryRevisionForm.tsx
  client/src/components/diary-revision/DiaryRevisionImgUpload.tsx
  client/src/components/diary-revision/ExistingImg.tsx
  client/src/components/diary-revision/NewImg.tsx
  client/src/utils/image.ts
Labels: 🐛 debug, 🍇 fe
