Repository sojinjang/podo-log, pull requests merged in 2023-04, with the labels that each got.

#221 [BE] CI/CD code 추가
  .github/workflows/server.yml
  server/appspec.yml
  server/scripts/after-deploy.sh
Labels: ✨ enhancement, 🎒 be

#223 [FE] 웹 성능 최적화 - SEO, Accessbility 개선
  client/public/index.html
  client/src/components/book-list/BookButton.tsx
  client/src/components/book-list/HeartDiaryButton.tsx
  client/src/components/book-list/NewBookButton.tsx
  client/src/components/book-list/PointingFinger.tsx
  client/src/components/book-setting/MemberProfile.tsx
  client/src/components/book/DiaryContainer.tsx
  client/src/components/book/NewDiaryButton.tsx
  client/src/components/book/SettingButton.tsx
  client/src/components/common/BackButton.tsx
  client/src/components/common/NavBar.tsx
  client/src/components/common/diary/DiarySection.tsx
  client/src/components/common/diary/Sticker.tsx
  client/src/components/diary-detail/Comment.tsx
  client/src/components/diary-detail/DeleteModal.tsx
  client/src/components/diary-detail/EditingSticker.tsx
  client/src/components/diary-detail/StickerSection.tsx
  client/src/components/diary-revision/ExistingImg.tsx
  client/src/components/diary-revision/NewImg.tsx
  client/src/components/grape/MyGrapeNum.tsx
  client/src/components/grape/PackageDetail.tsx
  client/src/components/grape/StickerPackList.tsx
  client/src/components/home/SNSLoginContainer.tsx
  client/src/components/my-page/MyInfoSection.tsx
  client/src/components/new-book/BookIcon.tsx
  client/src/components/new-diary/DiaryImgUpload.tsx
  client/src/pages/BookRevision.tsx
  client/src/pages/NewBook.tsx
  client/src/pages/NotFound.tsx
Labels: 🍇 fe, ♻️ refactor

#229 [FE] 댓글 로딩 상태 Skeleton UI 적용
  client/src/components/diary-detail/Comment.tsx
  client/src/components/diary-detail/CommentSection.tsx
  client/src/components/diary-detail/CommentsSkeleton.tsx
  client/src/pages/DiaryDetail.tsx
Labels: ✨ enhancement, 🍇 fe
